### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by MatthieuDartiailh** [LabPy/labpy-discussion#3]
We need unit testing. The question is using what library and what CI system and where do the tests live.
I am in favor of : 
- having the test outside the package. As nothing will strongly depend on the os or hardware, I consider the basic user does not need them and they are mainly dedicated to the developper.
- py.test for testing : it has all the niceties of nose or unittest but allow writing simple assert statement and take care of generating nice errors report. Furthermore we can have log capture for free and a bunch a other plugin
- Travis CI for continuous integration. We do not need any windows specific testing so AppVeyor is not really making sense.

**Comment by hgrecco** [comment]
+1 on Travis.

I tend to use unittest (or unittest2 in Python 2.7) but I actually like py.test a lot. So I would be fine with that.

Regarding the location of the tests, I usually put them inside the package (as suggested [here](http://the-hitchhikers-guide-to-packaging.readthedocs.org/en/latest/creation.html)) so that people can run them if they want to (like numpy or scipy). I am not sure if this is important for projects like Lantz for the reasons that @MatthieuDartiailh suggested so I would be fine to put them outside.

I would suggest that, as others have suggested, that Message Based driver testing is done using PyVISA-sim (this would require that we build the simulated device for different drivers.)

**Comment by alexforencich** [comment]
+1 on py.test + travis.  This is what I use.  I also set up tox for running tests against multiple versions of python so that all of the tests can be run locally before pushing just to make sure that there isn't a cross-python-version issue.  Not sure if there is a simple way to do that without using tox, though.

**Comment by MatthieuDartiailh** [comment]
I am fine with using tox.

**Comment by MatthieuDartiailh** [comment]
@alexforencich  What is your opinion with respect to the tests location ?

**Comment by alexforencich** [comment]
I'm not sure what makes the most sense.  Obviously they need to be in the repo.  I don't think they need to be installed with the package, though.  However, if they are segmented out at the top level then it is slightly more difficult to correlate the tests with the modules they correspond to.  I don't really have a strong opinion on this one way or the other.

**Comment by MatthieuDartiailh** [comment]
What I usually do is to reproduce the package layout in the tests folder located at the root of the repo. That way it is easy to match tests to the related module.

**Comment by alexforencich** [comment]
Yeah, matching the directory structure definitely makes sense for a top-level tests folder.  Since it's a parallel tree it's a little bit more work to match the modules and tests.  However, I think keeping the tests out of the package is more important.  If that's what you're familiar with, then we might as well go with that.

**Comment by MatthieuDartiailh** [comment]
We seem to have an agreement. Shall we close and update the wiki ? @LabPy/owners

**Comment by alexforencich** [comment]
Sounds like a plan.

**Comment by MatthieuDartiailh** [comment]
I am closing as we seem to all agree. When https://github.com/LabPy/lantz_core/pull/1#issuecomment-76006768 is merged it would be great if somebody could setup Travis and perhaps coveralls too.

**Comment by bilderbuchi** [comment]
Should the project resurrect at some point, I can help with pytest and travis issues.

**Comment by MatthieuDartiailh** [comment]
The most up to date version of what can be found in lantz_core is now in https://github.com/Exopy/i3py. I do not see the point to revive this at the moment.

**Comment by bilderbuchi** [comment]
I see, thanks. I'd be curious, why the reimplementation in a different package instead of continuing here?

**Comment by MatthieuDartiailh** [comment]
Just because I was not willing to support the whole inheritance that goes with Lantz.

**Comment by bilderbuchi** [comment]
Ah I see. :-)
